### ISSUE TITLE
Error: Cannot find module 'eslint-config-vue'

### ISSUE THREAD

**Issue by nucamoz** [vuejs/eslint-config-vue#10]
I've installed linter-eslint in Atom, then npm install --save-dev eslint-config-vue eslint-plugin-vue, then edit .eslintrc with "extends"
```
Error: Cannot find module 'eslint-config-vue' Referenced from: /home/zman/udemy-vue/.eslintrc

Error: Cannot find module 'eslint-config-vue'
Referenced from: /home/zman/udemy-vue/.eslintrc
    at ModuleResolver.resolve (/home/zman/.atom/packages/linter-eslint/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/home/zman/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:478:33)
    at load (/home/zman/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:495:26)
    at configExtends.reduceRight.e (/home/zman/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:391:36)
    at Array.reduceRight (native)
    at applyExtends (/home/zman/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:362:28)
    at Object.load (/home/zman/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:529:22)
    at loadConfig (/home/zman/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:63:33)
    at new Config (/home/zman/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:229:42)
    at CLIEngine.executeOnText (/home/zman/.atom/packages/linter-eslint/node_modules/eslint/lib/cli-engine.js:741:28)
```

How to make it work?

**Comment by chrisvfritz** [comment]
This sounds like a problem with the Atom plugin's module resolution, not this package. Maybe it requires globally installed modules? Or a setting has to be configured?

**Comment by nucamoz** [comment]
Yes, I fixed it - need to install eslint both globally and local, not sure what make it fixed.
